spring:
  application:
    name: professionaltaxportal
  
  datasource:
    url: jdbc:postgresql://localhost:5432/professional_tax_db
    username: ptax_user
    password: ptax_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

cors:
  allowed-origins: "http://localhost:3000,http://localhost:3001"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    io.example.professionaltaxportal: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# Fast2SMS Configuration
fast2sms:
  api:
    key: qkb4hFHaKsSod8RX6pvMYPwc90ExltA5nVUWIfeizBu17QCGDyemc5QuFyR7zkOxAIglo6KqjU0EDtHh
    url: "https://www.fast2sms.com/dev/bulkV2"
    sender-id: "FSTSMS"
    route: "otp"
  otp:
    expiry-minutes: 5
    max-attempts: 3
    length: 6
